# Generated by Django 3.2.16 on 2023-01-18 17:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20230118_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='created_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
