# Generated by Django 3.2.16 on 2023-01-18 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_channel_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='created_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
