# Generated by Django 3.2.16 on 2023-01-18 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20230118_1913'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='permissions',
            field=models.CharField(choices=[('R', 'Read'), ('W', 'Write'), ('A', 'Admin')], default=('R', 'Read'), max_length=255),
        ),
    ]
