# Generated by Django 3.2.16 on 2023-01-23 18:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_message_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='sent_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
