# Generated by Django 3.2.16 on 2023-01-24 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_message_sent_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='join_date',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sent_date',
        ),
    ]
