# Generated by Django 3.2.16 on 2023-01-28 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20230124_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='permissions',
            field=models.CharField(choices=[(1, 'Read'), (2, 'Write'), (3, 'Admin')], default=1, max_length=255),
        ),
    ]
